AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda API Service - Sistema Kronos

Resources:
  ApiServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-kronos-apiservice
      CodeUri: src/
      Description: 'Lambda API Service - Autenticación JWT para Kronos'
      MemorySize: 512
      Timeout: 30
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Environment:
        Variables:
          MYSQL_HOST: kronos-app.ctiw48myq04p.us-east-1.rds.amazonaws.com
          MYSQL_USER: admin
          MYSQL_PASSWORD: KratosMilo123**
          MYSQL_DATABASE: kronos-app
          NODE_ENVIRONMENT: DEV
          JWT_SECRET: ''
          JWT_EXPIRES_IN: '30d'
      LoggingConfig:
        LogFormat: JSON
        ApplicationLogLevel: ERROR
        SystemLogLevel: WARN
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/lambda-kronos-apiservice:*'
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: /v1/fsm/auth/{proxy+}
            Method: any
        ApiRoot:
          Type: Api
          Properties:
            Path: /v1/fsm/auth
            Method: any
        ExternalApiProxy:
          Type: Api
          Properties:
            Path: /v1/fsm/external/{proxy+}
            Method: any
    Metadata:
      BuildMethod: makefile

Outputs:
  ApiServiceFunctionArn:
    Value: !GetAtt ApiServiceFunction.Arn
  ApiGatewayUrl:
    Description: URL del API Gateway para Kronos API Service
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
